#!/usr/bin/env python3
"""Extract xahaud's Hook float implementation into a standalone C++ unit.

  python3 test/extract_float.py <xahaud-src> > build/xfl_release.h

Copies, verbatim apart from mechanical renames:
  - namespace hook_float from src/xrpld/app/hook/HookAPI.h
  - every HookAPI::float_* method and the float internals from HookAPI.cpp,
    turned into free functions (HookAPI:: prefix and trailing const removed)
  - RETURN_IF_INVALID_FLOAT from applyHook.cpp
so test/native_float.cpp exercises the release code itself, not a re-implementation.
"""
import re, sys
root = sys.argv[1]
h = open(f"{root}/src/xrpld/app/hook/HookAPI.h").read()
cpp = open(f"{root}/src/xrpld/app/hook/detail/HookAPI.cpp").read()
app = open(f"{root}/src/xrpld/app/hook/detail/applyHook.cpp").read()

start = h.index("namespace hook_float {")
end = h.index("}  // namespace hook_float") + len("}  // namespace hook_float")
hf = h[start:end]

names = ["float_set", "float_multiply", "float_mulratio", "float_negate", "float_compare",
         "float_sum", "float_invert", "float_divide", "float_one", "float_mantissa",
         "float_sign", "float_int", "float_log", "float_root",
         "float_multiply_internal_parts", "mulratio_internal", "float_divide_internal", "double_to_xfl"]
bodies = []
for n in names:
    m = re.search(r"\n((?:inline )?(?:Expected<[^\n]*>|bool|int64_t|uint64_t)\s*\n)HookAPI::" + n + r"\((.*?)\n\}\n", cpp, re.S)
    if not m:
        sys.exit(f"extract_float: {n} not found")
    ret, rest = m.group(1).replace("inline ", ""), m.group(2)
    rest = re.sub(r"\)\s*const\s*\n\{", ")\n{", rest, count=1)
    bodies.append((n, "inline " + ret + n + "(" + rest + "\n}\n"))

# The only amendment-dependent line in the float code: substitute it with a
# compile-time switch so the check can be run with the amendment on AND off.
AMEND = "hookCtx.applyCtx.view().rules().enabled(fixFloatDivide)"
for i, (n, b) in enumerate(bodies):
    if "hookCtx" in b:
        if AMEND not in b:
            sys.exit(f"extract_float: unexpected hookCtx use in {n}")
        b = b.replace(AMEND, "(NATIVE_FIX_FLOAT_DIVIDE != 0)")
        if "hookCtx" in b:
            sys.exit(f"extract_float: unexpected hookCtx use in {n}")
        bodies[i] = (n, b)

mac = re.search(r"#define RETURN_IF_INVALID_FLOAT\(float1\).*?\n\s*\}\s*\n", app, re.S).group(0)

print("// GENERATED by test/extract_float.py from xahaud — release float code, verbatim.")
print("#pragma once")
print("#include <xrpl/basics/Expected.h>\n#include <xrpl/protocol/IOUAmount.h>\n#include <xrpl/hook/Enum.h>")
print("#include <cfenv>\n#include <cmath>\n#include <limits>\n#include <type_traits>\n#include <stdexcept>")
print("#include <boost/multiprecision/cpp_int.hpp>\n#include <boost/multiprecision/cpp_dec_float.hpp>")
print("#ifndef NATIVE_FIX_FLOAT_DIVIDE\n#error define NATIVE_FIX_FLOAT_DIVIDE=0 or 1\n#endif")
# The alias is copied from HookAPI.h verbatim.
alias = re.search(r"using HookReturnCode = [^;]+;", h).group(0)
print("namespace hook {\nusing namespace ripple;\nusing namespace hook_api;\n" + alias)
print(hf)
print("using namespace hook_float;")
# forward declarations so call order doesn't matter
for n, b in bodies:
    sig = b.split("\n{", 1)[0]
    print(sig + ";")
for n, b in bodies:
    print(b)
print("}  // namespace hook")
print(mac)
