// Chaos Monkey — generate a harness's code from its cases.mjs (shared by C and D).
//
//   node tools/gen-cases.mjs hookapi
//   node tools/gen-cases.mjs floatsto
//
// From src/<h>/cases.mjs writes:
//   src/<h>/cases.gen.h      CASE_COUNT, EXPECTED[]   (file scope)
//   src/<h>/cases.gen.inc    the dispatch switch      (inside hook())
//   dist/dashboard-<h>.html  dashboard with the case labels baked in
//   build/native_<h>_cases.inc  X(id, expr) lines for cases with a `native` expr
//
// Fails on: duplicate or malformed ids, unknown error names, a case count
// other than 64, an expected value outside int64, or a dashboard over 4096 bytes.

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const h = process.argv[2];
const die = (m) => { console.error(`gen-cases(${h}): ` + m); process.exit(1); };
if (!/^[a-z]+$/.test(h || "")) die("usage: node tools/gen-cases.mjs <harness>");

const { CASES } = await import(pathToFileURL(path.resolve(`src/${h}/cases.mjs`)).href);

const ERR = {};
for (const m of fs.readFileSync("include/hook/error.h", "utf8").matchAll(/#define\s+([A-Z_]+)\s+(-\d+)/g))
  ERR[m[1]] = BigInt(m[2]);

const N = 64;
if (CASES.length !== N) die(`expected ${N} cases, found ${CASES.length}`);
const I64_MIN = -(1n << 63n), I64_MAX = (1n << 63n) - 1n;
const seen = new Set();
const exp = CASES.map((c, i) => {
  if (!/^[a-z0-9]+\.[A-Za-z0-9]+$/.test(c.id)) die(`case ${i}: id "${c.id}" must be <group>.<name>`);
  if (seen.has(c.id)) die(`duplicate id ${c.id}`);
  seen.add(c.id);
  let v;
  if (typeof c.exp === "string" && c.exp in ERR) v = ERR[c.exp];
  else if (typeof c.exp === "number" && Number.isSafeInteger(c.exp)) v = BigInt(c.exp);
  else if (typeof c.exp === "string" && /^-?\d+$/.test(c.exp)) v = BigInt(c.exp);
  else die(`case ${i} ${c.id}: exp must be an error name, a safe integer, or a decimal string`);
  if (v < I64_MIN || v > I64_MAX) die(`case ${i} ${c.id}: exp out of int64 range`);
  return v;
});
// INT64_MIN cannot be written as a literal; nothing here needs it.
const lit = (v) => (v < 0n ? `(${v}LL)` : `${v}LL`);

const hdr = `/* GENERATED by tools/gen-cases.mjs from src/${h}/cases.mjs — do not edit. */
#ifndef CHAOS_${h.toUpperCase()}_CASES_GEN_H
#define CHAOS_${h.toUpperCase()}_CASES_GEN_H
#define CASE_COUNT ${N}
static const int64_t EXPECTED[CASE_COUNT] = {
${CASES.map((c, i) => `    /* ${String(i).padStart(2)} ${c.id.padEnd(9)} */ ${lit(exp[i])},`).join("\n")}
};
#endif
`;

// Two-level switch (8 groups x 8) keeps WASM block depth shallow.
let inc = `/* GENERATED by tools/gen-cases.mjs from src/${h}/cases.mjs — do not edit.
 * Included inside hook(); expects int c and int64_t actual in scope. */
switch (c >> 3)
{
`;
for (let g = 0; g < N / 8; g++) {
  inc += `case ${g}:\n    switch (c & 7)\n    {\n`;
  for (let s = 0; s < 8; s++) {
    const i = g * 8 + s, k = CASES[i];
    inc += `    case ${s}: actual = ${k.call}; break; /* ${i} ${k.id} */\n`;
  }
  inc += `    default: break;\n    }\n    break;\n`;
}
inc += `default: break;\n}\n`;

fs.writeFileSync(`src/${h}/cases.gen.h`, hdr);
fs.writeFileSync(`src/${h}/cases.gen.inc`, inc);

const natives = CASES.filter((c) => c.native);
if (natives.length) {
  fs.mkdirSync("build", { recursive: true });
  fs.writeFileSync(`build/native_${h}_cases.inc`, natives.map((c) => `X("${c.id}", ${c.native})`).join("\n") + "\n");
}

// Dashboard labels, grouped by prefix: "ha:oob,ok|ln:oob,ok|..." (order preserved).
const groups = [];
for (const c of CASES) {
  const [p, rest] = c.id.split(".");
  if (groups.length && groups.at(-1)[0] === p) groups.at(-1)[1].push(rest);
  else groups.push([p, [rest]]);
}
const labels = groups.map(([p, r]) => p + ":" + r.join(",")).join("|");
const tpl = fs.readFileSync(`dashboard-${h}/dashboard-${h}.html`, "utf8");
if (!tpl.includes("__CASES__")) die(`dashboard-${h}.html has no __CASES__ placeholder`);
const page = tpl.replace("__CASES__", labels);
// The publisher substitutes the address (worst case 35 chars) and a 64-char namespace.
const size = Buffer.byteLength(page.replace("FUZZER", "r".padEnd(35, "A")).replace("NAMESPACE", "B".repeat(64)));
if (size > 4096) die(`dashboard renders to ${size} bytes; the AppLoader limit is 4096`);
fs.mkdirSync("dist", { recursive: true });
fs.writeFileSync(`dist/dashboard-${h}.html`, page);

console.log(`gen-cases(${h}): ${N} cases -> cases.gen.h, cases.gen.inc` +
  (natives.length ? `, ${natives.length} native` : "") + `; dashboard ${size}/4096 bytes`);
